### ISSUE TITLE
Add prioritizing to the display server

### ISSUE THREAD

**Issue by sqozz** [Bytewerk/Lumino#1]
It would be nice if the display server could support prioritizing of connecting clients.
The idea is that the client with the lowest priority is allowed to paint on the Lumino.
Every client that stets its id and that is already in use by another client should get a response like "ID already in use" so he can choose a new random one.

**Comment by cfr34k** [comment]
Implemented and deployed with commit 6160489fa072ce46a104e4f8bef9c718bb314f9f . Testing will be done in production ;-) .

**Comment by cfr34k** [comment]
Tested long enough :grin:
